### ISSUE TITLE
请问您的模型中出现nan是如何解决的？

### ISSUE THREAD

**Issue by zengrui324** [xxx-007/image#1]
请问你模型出现nan是怎么解决的 啊？我目前是获取UR5_connection#0的力的参数时print出来是nan，然后使用rl生成的动作也就是nan了，就导致模型在vrep中消失了。谢谢

**Comment by xxx-007** [comment]
x1 = torch.where(torch.isnan(x1), torch.full_like(x1, 1e-4), x1)
使用torch中的一个函数，用一个数取代nna值，具体使用您可以查一下这个函数的用法！

**Comment by zengrui324** [comment]
好的，感谢
